CREATE TABLE promoter(
	cpf BIGINT(11) PRIMARY KEY NOT NULL,
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	senha VARCHAR(8) NOT NULL,
	endereco VARCHAR(80)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;