CREATE TABLE evento(
	id_evento int(20) PRIMARY KEY AUTO_INCREMENT,
	descricao VARCHAR(50) NOT NULL,
	data VARCHAR(10) NOT NULL,
	horario VARCHAR(5) NOT NULL,
	local VARCHAR(50) NOT NULL,
	tipo VARCHAR(20) NOT NULL,
	traje VARCHAR(20) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;